import Link from 'next/link'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Sidebar from '../components/sidebar'
import { ReactElement, JSXElementConstructor, ReactFragment, ReactPortal } from 'react'
import sidebarStyle from '../styles/TitleSidebar.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import React, { useEffect, useState } from "react";
import SlidingPane from "react-sliding-pane";
import "react-sliding-pane/dist/react-sliding-pane.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faBars } from "@fortawesome/free-solid-svg-icons"
import { useTheme } from "@/lib/theme";

const inter = Inter({ subsets: ['latin'] })


export default function Template(props: { children: string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal | null | undefined, pagename: string }) {
    const [state, setState] = useState({
        isPaneOpen: false
    });
    const { theme, toggleTheme } = useTheme();
    const themeContent = theme == "light" ? "#16617F" : "#280000";
    return (
        <>
            <Head>
                <title>Masa Fujita</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
                <meta name="theme-color" content={themeContent}></meta>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main} style={{
                // backgroundImage: `url(${bgUrl.src})`,
                backgroundSize: 'cover',
                // paddingLeft: 'env(safe-area-inset-left)',
                // paddingRight: 'env(safe-area-inset-right)',
            }}>
                <div className={styles.maincontainer}>
                    <div className={styles.navbarButtonWrap}>
                        <a onClick={() => setState({ isPaneOpen: true })} className={styles.navbarButton}>
                            <FontAwesomeIcon icon={faBars} />
                        </a>
                        <SlidingPane
                            // className="some-custom-class"
                            className={styles.overlay}
                            isOpen={state.isPaneOpen}
                            // title="Hey, it is optional pane title.  I can be React component too."
                            // subtitle="Optional subtitle."
                            from="left"
                            hideHeader
                            width="300px"
                            onRequestClose={() => {
                                // triggered on "<" on left top click or on outside click
                                setState({ isPaneOpen: false });
                            }}
                        >
                            <div className={styles.contentArea}>
                                <div className={sidebarStyle.sidebar}>
                                     <Link href="/">{props.pagename == "home" ? "+" : "-"} Home</Link>
                                     <Link href="/hello">{props.pagename == "hello" ? "+" : "-"} Hello</Link>
                                     <Link href="/academia">{props.pagename == "academia" ? "+" : "-"}  Academia</Link>
                                     <Link href="/carrer">{props.pagename == "carrer" ? "+" : "-"} Carrer</Link>
                                     <Link href="/works">{props.pagename == "works" ? "+" : "-"} Open-source Works</Link>
                                     <Link href="/qualifications">{props.pagename == "qualifications" ? "+" : "-"} Qualifications</Link>
                                     <Link href="/other">{props.pagename == "other" ? "+" : "-"} Other</Link>
                                     <button onClick={ toggleTheme } className={styles.darkModeButtonWrap}></button>
                                </div>
                            </div>
                        </SlidingPane>
                    </div>
                    <div>
                        <div className={styles.name}>
                            <div>
                                <span>Welcome to the page of:</span>
                                <h1 className={inter.className}><b>Masa</b> Fujita</h1>
                            </div>
                        </div>
                    </div>
                    <div className={styles.contentArea}>
                        <Sidebar title={props.pagename}/>
                        {props.children}
                    </div>
                </div>
            </main >
        </>
    )
}

